# port
server:
  http.port: 8000
  port: 18000
  domain: https://10.224.81.70:6443/sample-system
  servlet:
    context-path: /sample-system
    session:
      cookie:
        name: SAMPLE_SSESSION
      timeout: 30m
  ssl:
    key-store: D:\tiennd\app\Apache24\conf\ssl\fiisw_cnsbg_efoxconn_com.pfx
    key-store-password: Foxconn168!!
    #    key-alias: fiisw.foxconn.com.vn
    key-store-type: PKCS12
    enabled: true

# security
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ws-system
      clientSecret: Foxconn168!!
      accessTokenUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/token
      userAuthorizationUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/authorize
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/api/user/information
      userChangePassUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/api/user/change-password
      tokenInfoUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/check_token
    logoutUrl: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/logout

# db
spring:
  datasource:
#    url: jdbc:sqlserver://10.224.81.70:3000;databaseName=uthing
#    username: 8170sql
#    password: Foxconn123
    url: jdbc:sqlserver://10.224.81.145:3000;databaseName=uthing
    username: fii
    password: Foxconn168!!
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      minimumIdle: 0
      connectionTestQuery: SELECT 1
      validationTimeout: 300000
  jpa:
    show-sql: true
#    properties.hibernate.format_sql: true
    properties.hibernate.use_nationalized_character_data: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    default-domain: sample-system
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy/MM/dd HH:mm:ss
  rabbitmq:
    host: 10.224.81.142
    port: 5672
    username: rabbitmq
    password: Foxconn168!!
  servlet:
    multipart:
      location: D:/tiennd/data/project/ws/
      enabled: true
      max-file-size: 64MB
      max-request-size: 128MB

# cron
batch:
  cron:
    sync-data: 0 9/10 * * * *
    sync-cpk: 45 0/30 * * * *
    sync-daily: 0 30 11 * * *
    check-warning: 0 5/10 * * * *
    outdated-tracking: 0 35 7,19 * * *
    check-maintain-schedule: 0 30 7 * * *
    check-maintain-spec: 0 0/15 0 * * *
    sync-hourly: 30 45 * * * *
    sync-hr-meal: 0 0 9 * * *
    send-mail-hr-meal: 0 15 10 * * *
    sync-daily-remain-re: 0 30 7 * * *
    backup-hr-duty-data : 0 0 0 15 * *
    sync-daily-balance-re: 0 58 23 * * *
  fixed:
    check-locked: 30000
    check-notify-auto: 300000
    tracking: 60000
    notify-message: 60000
    hr-card-history: 3600000
    re-card-checkin: 3600000
  initial:
    check-locked: 54000
    check-notify-auto: 54000
    tracking: 108000
    notify-message: 72000
    hr-card-history: 3600000
    re-card-checkin: 1800000

b04:
  datasource:
    url: jdbc:h2:mem:b04;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
#    url: jdbc:sqlserver://10.224.69.103;databaseName=dbB04_Test;sendStringParametersAsUnicode=false
#    username: oper
#    password: wireless
#    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      maximumPoolSize: 2
      minimumIdle: 0
      connectionTestQuery: SELECT 1
      validationTimeout: 300000

nbbsfc:
  datasource:
    #    url: jdbc:oracle:thin:@10.239.89.252:1521:vnsfc
    url: jdbc:oracle:thin:@10.225.35.11:1521:vnsfc
    username: CQYR
    password: cqyieldrate
#    username: nbbyr
#    password: nbbyr19
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      maximumPoolSize: 2
      minimumIdle: 0
      connectionTestQuery: SELECT 1 FROM DUAL
      validationTimeout: 300000

# uploading
path:
  data: D:/tiennd/data/project/sample-system/

# logging
logging:
  path: logs/sample-system
  level:
    com.foxconn.fii: INFO
#    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    com.zaxxer.hikari: DEBUG