# port
server:
  http.port: 8000
  port: 18000
  domains: >
    https://fiisw.cnsbg.efoxconn.com:6443/sample-system
    https://10.224.81.70:6443/sample-system,
  servlet:
    context-path: /sample-system
    static-path: /ws-data
    session:
      cookie:
        name: SAMPLE_SESSION
      timeout: 30m
  ssl:
    key-store: D:\tiennd\app\Apache24\conf\ssl\fiisw_cnsbg_efoxconn_com.pfx
    key-store-password: Foxconn168!!
    #    key-alias: fiisw.foxconn.com.vn
    key-store-type: PKCS12
    enabled: true

# security
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ws-system
      clientSecret: Foxconn168!!
      accessTokenUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/token
      userAuthorizationUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/authorize
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/api/user/information
      userChangePassUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/api/user/change-password
      tokenInfoUri: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/oauth/check_token
    logoutUrl: https://fiisw.cnsbg.efoxconn.com:6443/oauth-service/logout

# db
spring:
  datasource:
#    url: jdbc:h2:mem:b04;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
    url: jdbc:sqlserver://10.224.81.145:3000;databaseName=fiistore
    username: fii
    password: Foxconn168!!
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    hikari:
      connectionTimeout: 5000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      minimumIdle: 0
      connectionTestQuery: SELECT 1
      validationTimeout: 5000
  jpa:
    show-sql: true
#    properties.hibernate.format_sql: true
    properties.hibernate.use_nationalized_character_data: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    default-domain: sample-system
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy/MM/dd HH:mm:ss
  rabbitmq:
    host: 10.224.81.142
    port: 5672
    username: rabbitmq
    password: Foxconn168!!
  servlet:
    multipart:
      location: D:/tiennd/data/project/ws/
      enabled: true
      max-file-size: 64MB
      max-request-size: 128MB

# cron
batch:
  cron:
    sample: 0 9/10 0 * * *
  fixed:
    sample: 30000
  initial:
    sample: 5400000

mssql:
  datasource:
    url: jdbc:h2:mem:b04;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
#    url: jdbc:sqlserver://10.224.69.103;databaseName=dbB04_Test;sendStringParametersAsUnicode=false
#    username: oper
#    password: wireless
#    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 5000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      maximumPoolSize: 2
      minimumIdle: 0
      connectionTestQuery: SELECT 1
      validationTimeout: 5000

oracle:
  datasource:
    url: jdbc:h2:mem:b04;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
#    url: jdbc:oracle:thin:@10.225.35.11:1521:vnsfc
#    username: CQYR
#    password: cqyieldrate
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 5000
      idleTimeout: 30000
      maxLifetime: 60000
      minimumPoolSize: 0
      maximumPoolSize: 2
      minimumIdle: 0
      connectionTestQuery: SELECT 1 FROM DUAL
      validationTimeout: 5000

# uploading
path:
  data: D:/tiennd/data/project/sample-system/
  temp: D:/tiennd/temp/project/sample-system/

# logging
logging:
  path: logs/sample-system
  level:
    com.foxconn.fii: INFO
#    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    com.zaxxer.hikari: DEBUG